### ISSUE TITLE
XXE DoS Can't do it in Kali,Help

### ISSUE THREAD

**Issue by yanhuasanyuexyz** [juice-shop/pwning-juice-shop#115]
I use this
file:///dev/random)
But it can't be used, can you provide other solutions, thank you!

**Comment by bkimminich** [comment]
For support questions or help with challenges, please do not use GitHub issues but ask on Slack or Matrix. Links see https://owasp-juice.shop. Also please add logs etc. because you message above doesn't help providing help for you.
