### ISSUE TITLE
Bug on Gitbook.io in CTF.md Part 1

### ISSUE THREAD

**Issue by digitalarche** [juice-shop/pwning-juice-shop#87]
Online you have :

Non-interactive generator mode

Instead of answering questions in the CLI you can also provide your desired configuration in a file with the following straightforward format:

ctfFramework: CTFd | FBCTF | RootTheBox
juiceShopUrl: https://juice-shop.herokuapp.com
ctfKey: https://raw.githubusercontent.com/bkimminich/juice-shop/master/ctf.key # can also be actual key instead URL
countryMapping: https://raw.githubusercontent.com/bkimminich/juice-shop/master/config/fbctf.yml # ignored for CTFd and RootTheBox
insertHints: none | free | paid
insertHintUrls: none | free | paid # optional for FBCTF

BUT in github you have one line more : ;) 

insertHintSnippets: none | free | paid # optional for FBCTF

Must peharps deploying at new.

**Comment by bkimminich** [comment]
Oh, that's not good... I'll check if the pipeline to deploy might have silently failed. Thanks!

**Comment by bkimminich** [comment]
Oh no wait, GitBook.io is where you're looking? That is not the official page, it's a dead branch.

The official location is https://pwning.owasp-juice.shop/part1/ctf.html for a long time already. Where did you find a link to GitBook.io? Maybe I missed one somewhere.

I'll delete the GitBook.io project to be sure nobody accidentally goes there and Google doesn't recommend it.

**Comment by bkimminich** [comment]
Okay, now I'm lost: https://app.gitbook.com/@bkimminich/s/juice-shop/part-i-hacking-preparations/ctf also has the line you mention as missing.

Where are you looking? Please provide a link.

**Comment by bkimminich** [comment]
I think I found it - https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/ctf.html - the old GitBook page still has old content as it hasn't been updated since version 10.1.0 I'll try to pull that down from the Interwebs...

**Comment by digitalarche** [comment]
But then what the real and good URL and stuff for the Gitbook ? ;)

**Comment by bkimminich** [comment]
See https://github.com/juice-shop/pwning-juice-shop/issues/87#issuecomment-919690198

or just go to

https://pwning.owasp-juice.shop

All relevant and latest links are also on our website https://owasp-juice.shop.
