### ISSUE TITLE
[🐛] Password support wrong in KeePass file

### ISSUE THREAD

**Issue by nixpc** [juice-shop/pwning-juice-shop#93]
# :bug: Bug report

## Description

The password in `ftp/incident-support.kdbx` is not the same as in `data/static/users.yml`. If you take a look at the solution (https://pwning.owasp-juice.shop/appendix/solutions.html#log-in-with-the-support-teams-original-user-credentials) you can also see that the password in step 16 is also different than the one in the screenshot.

### Is this a regression?

Introduced in 0170851928bfd0f360bda2aa7bbedbe33e704967 .

## :deciduous_tree: Your Environment

Docker bkimminich/juice-shop
<pre><code>

                "org.opencontainers.image.authors": "Bjoern Kimminich <bjoern.kimminich@owasp.org>",
                "org.opencontainers.image.created": "”2022-02-08T22:38:10Z”",
                "org.opencontainers.image.description": "Probably the most modern and sophisticated insecure web application",
                "org.opencontainers.image.documentation": "https://help.owasp-juice.shop",
                "org.opencontainers.image.licenses": "MIT",
                "org.opencontainers.image.revision": "0b9b6f7",
                "org.opencontainers.image.source": "https://github.com/juice-shop/juice-shop",
                "org.opencontainers.image.title": "OWASP Juice Shop",
                "org.opencontainers.image.url": "https://owasp-juice.shop",
                "org.opencontainers.image.vendor": "Open Web Application Security Project",
                "org.opencontainers.image.version": "13.2.2"
</code></pre>

**Comment by bkimminich** [comment]
And it turns out that the KeePass file **and** the screenshot were both wrong, and I seem to have "tested" manually with the password from the YAML rather than the one from KeePass... 🤦‍♂️ ... ok, this will be fixed with the next version of Juice Shop. Thanks again!!!

**Comment by nixpc** [comment]
Yeah I can see how my bug report may have been a bit unclear, sorry about that 😅

Thanks for making Juice Shop, I'm having a blast playing through it :)
